# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-backend
spec:
  template:
    metadata:
      labels:
        version: blue
    spec:
      containers:
        - name: crud-backend
          image: siva9666/crud:backend-v1

          
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-frontend
spec:
  template:
    metadata:
      labels:
        version: blue
    spec:
      containers:
        - name: crud-frontend
          image: siva9666/crud:frontend-v1
---
# Redis StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crud-redis
spec:
  template:
    metadata:
      labels:
        version: blue
---
# MySQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crud-mysql
spec:
  template:
    metadata:
      labels:
        version: blue
    spec:
      containers:
        - name: crud-mysql
          image: siva9666/crud:mysql-v1
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: crud-frontend
spec:
  selector:
    app: crud-frontend
    version: blue
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: crud-backend
spec:
  selector:
    app: crud-backend
    version: blue
---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: crud-redis
spec:
  selector:
    app: crud-redis
    version: blue
---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: crud-mysql
spec:
  selector:
    app: crud-mysql
    version: blue
