apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/mysql.yaml
  - ../../../base/redis.yaml
  - ../../../base/secrets.yaml
patches:
   - path: mysql-patch-statefulset.yaml
     target:
       kind: StatefulSet
       name: crud-mysql
   - path: redis-patch-statefulset.yaml
     target:
       kind: StatefulSet
       name: crud-redis